export enum ActionTypes {
  LOAD_SOLUTION,
  TOGGLE_FILE,
  OPEN_FEEDBACK,
  PING,
  NEXT_EXERCISE,
  UPDATE_SINGLE_TEST_RESULT,
  SET_TEST_LIST,
  UPDATE_CODE,
  SELECT_EXERCISE,
  INIT_STATE,
  SELECT_MILESTONE,
  SEND_FEEDBACK,
  SIMULATE_STATE,
  SET_AUTH
}
